[package]
name = "hyprland-barinfo"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "~1.0"
bpaf = "~0.7"
regex = "~1.7"
serde = { version = "~1.0", features = [ "derive" ] }
serde_json = "~1.0"
