[package]
name = "hyprland-barinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "~1.0"
bpaf = "~0.6"
regex = "~1.6"
serde = { version = "~1.0", features = [ "derive" ] }
serde_json = "~1.0"
